#!/bin/bash

URL=https://plancky--munshi-machine-entrypoint.modal.run 
YT_VIDEO=https://www.youtube.com/watch?v=u_WPAzGvF7Y

curl -d "{\"url\":\"${YT_VIDEO}\"}" -H 'Content-Type: application/json' -X POST $URL/transcribe
echo "\\n"